language: cpp

branches:
  only:
    - master
    - /stable-.*/

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - svn checkout --non-interactive http://crosswire.org/svn/sword/trunk sword-trunk
  - cd sword-trunk
  - mkdir b
  - cd b
  - cmake ..
  - make
  - sudo make install
  - cd ../..

install:
  - wget http://www.cmake.org/files/v2.8/cmake-2.8.9.tar.gz
  - tar -xzf cmake-2.8.9.tar.gz
  - cd cmake-2.8.9
  - ./bootstrap
  - make
  - sudo make install
  - cd ..
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev qt4-qmake libclucene-dev

script:
  - mkdir b
  - cd b
  - /usr/local/bin/cmake ..
  - make
  - sudo make install

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "VjsU8+6Sca7TXbR5zQstHw6eb4Dv0ZifqE29DRT+n64VKxAWFaWazJ4VJNlHvd8ChiJRfFcXVVXfNgNMAHE/JJHt1GgSPwIqSEE2mQh+7tqfSeBV/5yBkF7Fs4QIOrWjdEhEHTt0+wc6wtoVghEHvWlk3Lymb4x0UQDZtz/a4cI="

addons:
  coverity_scan:
    project:
      name: "bibletime/bibletime"
      description: "BibleTime build submitted via Travis CI"
    notification_email: bibletime-coverity@heh.ee
    build_command_prepend: "mkdir b && cd b && /usr/local/bin/cmake .."
    build_command:   "make && sudo make install"
    branch_pattern: /.*_coverity_scan$/

notifications:
  irc: "chat.freenode.net#bibletime"
