sudo: required
dist: trusty
language: cpp

branches:
  only:
    - master
    - master_coverity_scan
    - /^stable-.*$/

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - wget --no-check-certificate http://www.cmake.org/files/v3.1/cmake-3.1.2-Linux-x86_64.sh
  - sudo bash ./cmake-3.1.2-Linux-x86_64.sh --prefix=/usr/local/ --skip-license --exclude-subdir
  - sudo add-apt-repository ppa:beineri/opt-qt57-trusty --yes
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - gpg --keyserver pgpkeys.mit.edu --recv-key 15CF4D18AF4F7421
  - gpg -a --export 15CF4D18AF4F7421 | sudo apt-key add -
  - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main' --yes
  - sudo add-apt-repository 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main' --yes
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa --yes
  - sudo apt-get update
  - if [ "$CXX" = "g++" ]; then sudo apt-get install --yes --force-yes g++-4.9; else sudo apt-get install --yes --force-yes clang-3.9; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; else export CXX="clang++-3.9" CC="clang-3.9"; fi
  - sudo apt-get install --yes --force-yes cmake libclucene-dev qt57base qt57declarative qt57svg qt57tools qt57webengine qt57xmlpatterns
  - source /opt/qt57/bin/qt57-env.sh
  - svn checkout --non-interactive http://crosswire.org/svn/sword/trunk sword-trunk
  - cd sword-trunk
  - mkdir b
  - cd b
  - cmake ..
  - make
  - sudo make install
  - export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
  - cd ../..

script:
  - if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then mkdir b && cd b && /usr/local/bin/cmake .. && make && sudo make install; fi

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "FmufrIN8L4Ptfbn0Lw/1S7fKnPxpvv7t9KEN5XhQ3lwW5Qir7mGe2r87biaKyjo15VNc4bizA2wR63YUXz6JPMETwYPahKSlW2tAsHmJTOwyweNW7zkKf6Iwrf9vYaMZyOpR2jRkD9Ko8vd4BpIw4FF6X/vaJqfnvQyIOiDGFr8="

addons:
  coverity_scan:
    project:
      name: "bibletime/bibletime"
      description: "BibleTime build submitted via Travis CI"
    notification_email: bibletime-coverity@heh.ee
    build_command_prepend: "mkdir b && cd b && /usr/local/bin/cmake .."
    build_command: "cmake --build ."
    branch_pattern: .*_coverity_scan

notifications:
  irc: "chat.freenode.net#bibletime"
